translate icongenie pages
dongwa/quasar-docs-cn pull request #35
Opened 2023-05-05 15:18 UTC by yb6b

尝试翻译 Icon Genie 的5篇，意译较多，期待审查。

2023-05-06 16:18 UTC, dongwa requested changes
感谢贡献代码，这里可能需要做一些修改

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/installation.md
> +你也可以删除当前项目里的所有图标或启动画面图片，并让运行 Icon Genie v2。这样可以确保项目里所有的图片都是实际要用的。
您也可以删除项目里当前的所有图标或启动页图片，然后让 Icon Genie 来帮您重新生成，可以保证所有的图片都是 Quasar 应用实际需要的。

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/installation.md
> +最后，我们需要再次强调 `quality` 参数，它将决定你的图像有多好看以及有多大（KB）。
图像有多好看以及有多大 -> 图片质量和大小

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/introduction.md
> +你喜欢默认的 Quasar logo，我们也是。精致的图标是一个 app 的门面，但制作它却是度日如年。如何用你自己的 logo 代替默认的？
你可能像我们一样喜欢默认的 Quasar logo，但精致的图标是一个 app 的门面，您需要使用自己的 logo。

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/introduction.md
> +title: 图标精灵命令行
Icon Genie CLI（图标精灵命令行工具）

这样写可以增加 seo 关键词

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/introduction.md
> +desc: Quasar 工具，支持 100 多种格式，一键给你的 app 生成所有图标和启动画面。
Quasar 图标工具
同样为了增加 SEO 关键词

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/introduction.md
> +我们强烈建议 **为你的 Quasar CLI 生成的项目** 使用 Icon Genie CLI 。输入一个初始的图标，就能自动复制、缩放、压缩、并放置到合适的目录里。它还会在合适的时候提醒你，`/src/index.template.html` 文件要添加哪些标签。
输入 ->  提供

2023-05-06 16:18 UTC, dongwa commented on src/pages/icongenie/app-icons-list.md
> +desc: 用 Icon Genie CLI 根据具体的 Quasar 模式生成的应用图标及启动画面列表。
启动画面 可以考虑译为 “启动页” 或者 “启动页图片”

2023-05-07 02:12 UTC, yb6b commented
谢谢提醒，已经按要求改了。

2023-05-07 05:56 UTC, merged

2023-05-07 05:56 UTC, dongwa commented
感谢贡献代码😃